### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by jmealo** [mlaursen/react-md-redux#1]
I'm unable to get this to run, I had to install the following:
```shell
npm install -g webpack nodemon
npm install extract-text-webpack-plugin  stylelint-webpack-plugin babel-plugin-system-import-transformer nstall babel-plugin-transform-decorators-legacy babel-preset-stage-0 babel-preset-es2015
```

This got me as far as this:

**npm run start:production**
```shell
npm run start:production

> react-md-redux@0.0.1 start:production /root/react-md-redux
> npm run build && npm run start:prod


> react-md-redux@0.0.1 build /root/react-md-redux
> npm run clean && better-npm-run build


> react-md-redux@0.0.1 clean /root/react-md-redux
> rimraf dist/!\(favicon.ico\)

running better-npm-run in /root/react-md-redux
Executing script: build

to be executed: webpack --progress --display-error-details --config ./configs/webpack.config.js
/root/react-md-redux/node_modules/extract-text-webpack-plugin/schema/validator.js:11
		throw new Error(ajv.errorsText());
		^

Error: data['fallbackLoader'] should NOT have additional properties
    at validate (/root/react-md-redux/node_modules/extract-text-webpack-plugin/schema/validator.js:11:9)
    at ExtractTextPlugin (/root/react-md-redux/node_modules/extract-text-webpack-plugin/index.js:125:3)
    at Object.<anonymous> (/root/react-md-redux/configs/webpack.config.js:127:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)

npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-md-redux@0.0.1 build: `npm run clean && better-npm-run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-md-redux@0.0.1 build script 'npm run clean && better-npm-run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-md-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && better-npm-run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-md-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-md-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/react-md-redux/npm-debug.log

npm ERR! Linux 3.13.0-68-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start:production"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-md-redux@0.0.1 start:production: `npm run build && npm run start:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-md-redux@0.0.1 start:production script 'npm run build && npm run start:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-md-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && npm run start:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-md-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-md-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/react-md-redux/npm-debug.log
```

and 

**npm start**
```
npm start

> react-md-redux@0.0.1 start /root/react-md-redux
> better-npm-run start

running better-npm-run in /root/react-md-redux
Executing script: start

to be executed: nodemon ./index.js
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: index.js /root/react-md-redux/configs/**/* src/server.js src/utils/renderHtmlPage package.json nodemon.json
[nodemon] starting `node ./index.js`
/root/react-md-redux/node_modules/babel-core/lib/transformation/file/logger.js:41
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] /root/react-md-redux/configs/WIT.config.js: Unknown option: base.Children. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options.
    at Logger.error (/root/react-md-redux/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/root/react-md-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
    at OptionManager.init (/root/react-md-redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/root/react-md-redux/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/root/react-md-redux/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/root/react-md-redux/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Object.transformFileSync (/root/react-md-redux/node_modules/babel-core/lib/api/node.js:152:10)
    at compile (/root/react-md-redux/node_modules/babel-register/lib/node.js:118:20)
    at loader (/root/react-md-redux/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/root/react-md-redux/node_modules/babel-register/lib/node.js:154:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Environment:**
```
> node -v
v6.5.0
> npm -v
3.10.3
> uname -a
Linux spark-api1 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mlaursen** [comment]
I think this is because I haven't upgraded this since the final version of webpack 2 came out. I'll try to do the migration when I get some free time

**Comment by jmealo** [comment]
In the meantime, what version of Webpack is known to work here?

Thanks,
Jeff

**Comment by mlaursen** [comment]
If you can use `yarn` instead of `npm`, it should work without issue. Otherwise try to install the exact `webpack@2.1.0-beta.27`
